---
functional:
  - Возможность регистрации пользователя на сайте
  - Возможность авторизации пользователя на сайте по email
  - Возможность авторизации пользователя через профиль Github
  - Возможность авторизации пользователя через профиль Discord
  - Возможность выхода из профиля пользователя на сайте
  - Возможность восстановления пароля от профиля пользователя
  - Пользователь должен иметь возможность зайти в свой профиль
  - Пользователь должен иметь возможность перейти на сайт Hexlet из личного кабинета
  - Пользователь должен иметь возможность просматривать исходный код игры на Github
  - Пользователь должен иметь возможность перейти в Telegram Channel из личного кабинета
  - Пользователь должен иметь возможность участвовать в игре без регистрации
  - Пользователь должен иметь возможность создать новую игру
  - Пользователь должен иметь возможность создать новый турнир
  - Пользователь должен иметь возможность подключиться к игре, созданной другим участником
  - Пользователь должен иметь возможность выбрать уровень сложности игры
  - Пользователь должен иметь возможность выбрать соперника из списка
  - Пользователь должен иметь возможность выбрать соперника-бота
  - Пользователь должен иметь возможность принять приглашение в игру от другого пользователя
  - Пользователь должен иметь возможность зайти в запущенную игру в качестве зрителя
  - Пользователь должен иметь возможность выбрать язык программирования
  - Пользователь должен иметь возможность во время игры просматривать задачу на английском и русском языках
  - Пользователь должен видеть отсчет времени во время игры
  - Пользователь должен иметь возможность нажать кнопку для проверки своего решения во время игры
  - Пользователь должен иметь возможность сброса в редакторе во время игры
  - Пользователь должен иметь возможность сдаться сопернику во время игры
  - Пользователь должен иметь возможность продолжить игру в случае если второй игрок вылетел из игры
  - Пользователь должен иметь возможность выйти из игры и при необходимости снова подключиться к ней, пока игра не закончена
  - Пользователь должен иметь возможность менять язык программирования во время игры
  - Пользователь должен видеть редактор с кодом соперника в режиме он-лайн
  - В игре должен быть чат, в котором смогут общаться зарегистрированные пользователи
  - Каждый игрок должен видеть модальное окно с информацией о победителе после того, как один из игроков найдет верное решение
  - Пользователь должен иметь возможность доиграть до конца или выйти после того, как соперник нашел верное решение
  - Игрок-победитель должен иметь возможность остаться и просмотреть свой код ещё раз
  - Игрок-победитель должен иметь возможность выйти из игры
  - Кнопка проверки решения должна быть недоступна для игрока-победителя
  - Игра должна считаться полностью завершенной после того, как оба игрока вышли из неё
  - Завершенная игра должна быть доступна к просмотру в записи
  - Редактор для ввода кода должен выглядеть как проигрыватель
  - Проигравший пользователь должен иметь возможность предложить матч-реванш
  - На сайте должна быть возможность начисления очков пользователям
  - На сайте должен вестись рейтинг зарегистрированных пользователей за неделю, месяц и за всё время
  - Пользователь должен иметь возможность просматривать рейтинг пользователей
  - В рейтинге пользователей должен быть поиск по пользователю
  - В рейтинге пользователей должна быть сортировка по основным полям таблицы
  - На сайте должна отображаться информация о пользователях он-лайн
  - Пользователь должен иметь возможность просматривать информацию о турнирах
  - Пользователь должен иметь возможность просматривать историю завершенных игр
  - Пользователь должен иметь возможность отправлять сообщения в чатах
  - Пользователь должен иметь возможность взяться за выполнение задачи
  - На сайте должна быть возможность указать на баг или неточность
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь не может вносить изменения в код соперника
  - Пользователь не может вносить изменения в рейтинге
  - Пользователь не может вносить изменения в задание игры
  - При вводе некорректных данных при регистрации нового пользователя на сайте должно выводиться сообщение об ошибке
  - При вводе некорректных данных при авторизации пользователя на сайте должно выводиться сообщение об ошибке
